openapi: '3.0.2'
info:
  title: Git Demo Document
  version: '0.1'
paths:
  /test:
    summary: Test
    get: 
      responses:
        '200':
          description: Test get
components:
  responses:
    200OK:
      description: OK